[env:feather_rp2040_can]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_can
framework = arduino
extra_scripts = pre:scripts/platformio_sync_ino_defines.py
board_build.core = earlephilhower
lib_deps = autowp/MCP2515
build_flags = -DDRIVER_MCP2515

[env:feather_m4_can]
platform = atmelsam
board = adafruit_feather_m4_can
framework = arduino
extra_scripts = pre:scripts/platformio_sync_ino_defines.py
lib_deps = adafruit/Adafruit CAN
build_flags = -DDRIVER_SAME51 -std=gnu++14
build_unflags = -std=gnu++11

[env:esp32_twai]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/platformio_sync_ino_defines.py
build_flags = -DDRIVER_TWAI -std=gnu++17
build_unflags = -std=gnu++11

[env:m5stack-atomic-can-base]
extends = env:esp32_twai
board = m5stack-atom
build_flags = ${env:esp32_twai.build_flags} -DPIN_LED=27 -DTWAI_TX_PIN=GPIO_NUM_22 -DTWAI_RX_PIN=GPIO_NUM_19

[env:native]
platform = native
build_flags = -std=c++17 -DNATIVE_BUILD -DISA_SPEED_CHIME_SUPPRESS -DEMERGENCY_VEHICLE_DETECTION
test_ignore = test_native_force_fsd
test_filter = test_native_*

[env:native_force_fsd]
platform = native
build_flags = -std=c++17 -DNATIVE_BUILD -DISA_SPEED_CHIME_SUPPRESS -DEMERGENCY_VEHICLE_DETECTION -DFORCE_FSD
test_filter = test_native_force_fsd

[env:native_log_buffer]
platform = native
build_flags = -std=c++17 -DNATIVE_BUILD
test_filter = test_native_log_buffer
